# 服务器基本配置
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

# 数据源信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://localhost:3306/food-shop?serverTimezone=Asia/Shanghai
#    username: root
#    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      test-while-idle: true
      validation-query: select 'x'
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  servlet:
    multipart:
      # 文件上传大小限制为500Kb
      max-file-size: 512000
      # 请求大小限制为500Kb
      max-request-size: 512000
  profiles:
    active: dev
  session:
    store-type: redis

# mybatis配置
mybatis:
  type-aliases-package: com.xybh.pojo       # 所有POJO类所在的包路径
  mapper-locations: classpath:mapper/*.xml  # mapper映射文件所在的位置
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 通用Mapper 配置
mapper:
  mappers: com.xybh.my.mapper.MyMapper
  not-empty: false   #在进行数据库操作的时候,判断表达式 username!=null,是否追加username!=''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
