server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food-shop?serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl