server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food-shop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: aa88700420
