###
GET http://localhost:8088/items/refresh?itemSpecIds=meat-1006-spec-1,meat-1004-spec-1,meat-1004-spec-2

###
GET http://localhost:8088/items/commentLevel?itemId=cake-1001

###
GET http://localhost:8088/items/comments?itemId=cake-1001&level=&page=1&pageSize=10
