# 登录测试
POST http://localhost:8088/passport/login
Content-Type: application/json

{
  "username": "xybh",
  "password": "123456"
}



###
# 注册测试
POST http://localhost:8088/passport/regist
Content-Type: application/json

{
  "username": "lanwang",
  "password": "123456",
  "confirmPassword": "123456"
}

###
# 判断用户名是否存在
GET http://localhost:8088/passport/usernameIsExist?username=1
