server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/payment?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-wait: 60000
      test-while-idle: true
      validation-query: select 'x'
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xybh.pojo
  mapper-locations: classpath:mapper/*.xml

# 通用Mapper 配置
mapper:
  mappers: com.xybh.my.mapper.MyMapper
  not-empty: false   #在进行数据库操作的时候,判断表达式 username!=null,是否追加username!=''
  identity: MYSQL
# 分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
